---
galaxy_info:
  author: luukwindesheim
  description: Deployt een nginx webserver via Docker Compose
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
